import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Select from '@mui/material/Select';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>WashWorld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className='titleStyle'>Select location</h1>
          <FormControl sx={{ m: 1, minWidth: 200 }}>
            <InputLabel id="demo-simple-select-label">Location</InputLabel>
            <Select
              labelId="select-location-label"
              id="location-select"
              // value={location}
              label="Location"
              // onChange={handleChange}
            >
              <MenuItem>Dynamovej 10</MenuItem>
              <MenuItem>Dynamovej 22</MenuItem>
              <MenuItem>Aalborg hovedvej 19</MenuItem>
              <MenuItem>Køgevej 198</MenuItem>
            </Select>
          </FormControl>

        </div>
      </main>
    </>
  )
}
