import Head from 'next/head'
import { useState, useEffect } from 'react';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Select from '@mui/material/Select';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';


const inter = Inter({ subsets: ['latin'] })

interface Location {
  id: number;
  name: string;
  status: string;
}


export default function Home() {
  const [locations, setLocations] = useState<Location[]>([]); 

  useEffect(() => {
    fetch('https://b46f027d-3a5f-4de6-9075-5e861759e531.mock.pstmn.io/locations')
      .then(response => response.json())
      .then(data => setLocations(data.response.locations))
      .catch(error => console.log(error));
  }, []);

  return (
    <>
      <Head>
        <title>WashWorld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.center}>
        <h1 className='titleStyle'>Select location</h1>
        <FormControl sx={{ m: 1, minWidth: 200 }}>
          <InputLabel id="demo-simple-select-label">Location</InputLabel>
          <Select
            labelId="select-location-label"
            id="location-select"
            // value={location}
            label="Location"
            // onChange={handleChange}
          >
            {locations.map((location: Location) => (
              <MenuItem key={location.id} value={location.name}>
                {location.name}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      </div>
    </main>
    </>
  )
}
